name=MySensorLib
version=1.0.0
author=Charalampos Kiokpasoglou
maintainer=charalamposkiokpasoglou@gmail.com
sentence=Modular sensor library for Arduino/ESP32.
paragraph=Provides a common Sensor base class and classes for a DHT sensor and a photoresistor with LED, organized in subfolders.
category=Sensors
url=https://github.com/kioskun/iot-backbone-lab-exercises
